# @format
#
# Release to various browser extension stores

name: 'Release'

on:
  workflow_dispatch:
    inputs:
      increment_version:
        description: 'Increment Version'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - none
      chrome:
        description: 'Chrome Webstore'
        default: true
        type: boolean
      edge:
        description: 'Edge Add-ons Store'
        default: true
        type: boolean
      firefox:
        description: 'Firefox Add-ons Store'
        default: true
        type: boolean

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      INCREMENT: ${{ github.event.inputs.increment_version }}
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for git-cliff



      - name: Calculate Version Number
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          VERSION=${TAG#v}
          echo "latest version: $VERSION"
          if [ "$INCREMENT" != "none" ]; then
            VERSION=$(npx --yes semver -i "$INCREMENT" "$VERSION")
          fi
          echo "new version: $VERSION"
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Update Version
        run: |
          npm --no-git-tag-version --allow-same-version version ${{ steps.version.outputs.version }}
          MANIFEST=$(cat src/manifest_v2/manifest.json | jq ".version |= \"${{ steps.version.outputs.version }}\"")
          echo "$MANIFEST" > src/manifest_v2/manifest.json
          MANIFEST=$(cat src/manifest_v3/manifest.json | jq ".version |= \"${{ steps.version.outputs.version }}\"")
          echo "$MANIFEST" > src/manifest_v3/manifest.json

      - name: Commit
        run: |
          git add .
          git config user.email "developers@dddice.com"
          git config user.name "dddice"
          git commit --allow-empty -m "release: ${{ steps.version.outputs.tag }}-${{ github.run_number }}" || echo 'ok'
          git push

      - name: Tag
        if: inputs.increment_version != 'none'
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}

      - name: Tag (Force)
        if: inputs.increment_version == 'none'
        run: |
          git tag -f ${{ steps.version.outputs.tag }}
          git push -f origin ${{ steps.version.outputs.tag }}

      - name: Build Release
        run: |
          npm ci
          npm run build:manifest_v3
          npm run build:manifest_v2

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip manifest v3
        run: zip -9 -qq -r ../dddice-browser-extension-manifest-v3.zip *
        working-directory: manifest_v3

      - name: Zip manifest v2
        run: zip -9 -qq -r ../dddice-browser-extension-manifest-v2.zip *
        working-directory: manifest_v2

      - name: Cache Files
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.OS }}-cache-${{ steps.version.outputs.tag }}-${{ github.run_number }}

  change-log:
    name: Create Release with Change Log
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.OS }}-cache-${{ needs.release.outputs.tag }}-${{ github.run_number }}

      - name: Generate Changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --current --strip all
        env:
          OUTPUT: CHANGES.md

      - name: Set the release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          echo "RELEASE_BODY<<EOF" >>$GITHUB_OUTPUT
          echo "$r" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.release.outputs.tag }}
          name: ${{ needs.release.outputs.tag }}
          body: ${{ steps.release.outputs.RELEASE_BODY }}
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: dddice-browser-extension-manifest-v3.zip,dddice-browser-extension-manifest-v2.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  chrome:
    if: inputs.chrome == true
    name: Upload to Chrome Web Store
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.OS }}-cache-${{ needs.release.outputs.tag }}-${{ github.run_number }}

      - name: Publish Chrome
        uses: levigo/github-action-chrome-webstore-publish@v1.0
        with:
          extensionId: ${{ secrets.CHROME_WEB_STORE_APP_ID }}
          clientId: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          clientSecret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          refreshToken: ${{ secrets.GOOGLE_OAUTH_REFRESH_TOKEN }}
          inputFile: './dddice-browser-extension-manifest-v3.zip'
          doPublish: true
  edge:
    if: inputs.edge == true
    name: Upload to Edge Addons Store
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.OS }}-cache-${{ needs.release.outputs.tag }}-${{ github.run_number }}

      - name: Publish Edge
        uses: wdzeng/edge-addon@v2
        with:
          product-id: '4b7d0dc8-f01b-4136-bccd-ad6e23731042'
          zip-path: './dddice-browser-extension-manifest-v3.zip'
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          api-key: ${{ secrets.EDGE_API_KEY}}

  firefox:
    if: inputs.firefox == true
    name: Upload to Firefox Addons Store
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.OS }}-cache-${{ needs.release.outputs.tag }}-${{ github.run_number }}

      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{87033b3f-6fa3-4046-b74f-76053b40c231}'
          xpi: ./dddice-browser-extension-manifest-v2.zip
          manifest: manifest_v2/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}